import { Platform, StyleSheet } from 'react-native';
import { safeBottom, safeTop } from '../layout/responsive';
import { colors } from '../theme';

/** @deprecated Prefer useLayout().safeTop */
export const SAFE_TOP = safeTop();
/** @deprecated Prefer useLayout().footerPad / safeBottom */
export const SAFE_BOTTOM = safeBottom();

/** Shared native app surfaces — grouped cards, not web boxes. */
export const moduleStyles = StyleSheet.create({
  card: {
    borderWidth: 0,
    backgroundColor: colors.background.card,
    borderRadius: 16,
    padding: 14,
    marginTop: 10,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  cardTitle: {
    color: colors.text.heading,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: -0.2,
    flex: 1,
  },
  cardMeta: {
    color: colors.text.muted,
    fontSize: 12,
    marginTop: 3,
  },
  cardBody: {
    color: colors.text.body,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  pill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    backgroundColor: 'rgba(238,125,49,0.1)',
  },
  pillText: {
    color: colors.brand.orangeSoft,
    fontSize: 10,
    fontWeight: '700',
  },
  pillSuccess: {
    backgroundColor: colors.status.successBg,
  },
  pillSuccessText: {
    color: colors.status.success,
  },
  pillDanger: {
    backgroundColor: colors.status.errorBg,
  },
  pillDangerText: {
    color: colors.status.error,
  },
  pillMuted: {
    backgroundColor: colors.navy[800],
  },
  pillMutedText: {
    color: colors.text.muted,
  },
  actions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  actionBtn: {
    minWidth: '22%',
    flexGrow: 1,
    minHeight: 44,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: 'rgba(238,125,49,0.12)',
  },
  actionBtnText: {
    color: colors.brand.orangeSoft,
    fontSize: 13,
    fontWeight: '600',
  },
  contentIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: 'rgba(238,125,49,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlineContact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  actionBtnPrimary: {
    backgroundColor: colors.brand.orange,
  },
  actionBtnPrimaryText: {
    color: colors.white,
  },
  actionBtnSuccess: {
    backgroundColor: colors.status.successBg,
  },
  actionBtnSuccessText: {
    color: colors.status.success,
  },
  actionBtnDanger: {
    backgroundColor: colors.status.errorBg,
  },
  actionBtnDangerText: {
    color: colors.status.error,
  },
  actionBtnMuted: {
    backgroundColor: colors.navy[800],
  },
  actionBtnMutedText: {
    color: colors.text.muted,
  },
  empty: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 14,
    padding: 16,
    marginTop: 12,
  },
  emptyTitle: {
    color: colors.text.heading,
    fontSize: 14,
    fontWeight: '700',
  },
  emptyText: {
    color: colors.text.body,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },
  sectionTitle: {
    color: colors.text.heading,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 16,
  },
  sectionSubtitle: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 2,
  },
  fabRow: {
    marginTop: 6,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  primaryButton: {
    borderRadius: 14,
    backgroundColor: colors.brand.orange,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  primaryButtonDisabled: {
    opacity: 0.55,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  secondaryButton: {
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(217,119,42,0.35)',
    backgroundColor: 'rgba(238,125,49,0.08)',
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: colors.brand.orangeSoft,
    fontSize: 15,
    fontWeight: '600',
  },
  searchInput: {
    borderWidth: 0,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    color: colors.text.heading,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    fontSize: 16,
    marginTop: 8,
    shadowColor: '#0F172A',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  input: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border.hairline,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    color: colors.text.heading,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    fontSize: 16,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  label: {
    color: colors.text.muted,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 10,
    marginBottom: 5,
  },
  switchRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  switchLabel: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  hint: {
    color: colors.text.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  errorText: {
    color: colors.status.error,
    fontSize: 12,
    marginTop: 8,
    lineHeight: 17,
  },
  successText: {
    color: colors.status.success,
    fontSize: 12,
    marginTop: 8,
    lineHeight: 17,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    justifyContent: 'flex-end',
    paddingTop: SAFE_TOP,
  },
  modalSheet: {
    backgroundColor: colors.background.card,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 0,
    borderColor: 'transparent',
    maxHeight: '92%',
  },
  modalGrabber: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    marginTop: 10,
    marginBottom: 2,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border.hairline,
  },
  modalTitle: {
    color: colors.text.heading,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  modalClose: {
    color: colors.brand.orange,
    fontSize: 15,
    fontWeight: '700',
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // When rightAction sits on dark ScreenShell header
  headerActionOnDark: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  modalBody: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: SAFE_BOTTOM + 18,
  },
  menuGroup: {
    marginTop: 20,
  },
  menuGroupTitle: {
    color: colors.text.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: -0.1,
    marginBottom: 8,
    marginLeft: 12,
    textTransform: 'none',
  },
  menuCard: {
    borderRadius: 14,
    backgroundColor: colors.background.card,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  menuItem: {
    minHeight: 56,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border.hairline,
  },
  menuIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(238,125,49,0.12)',
  },
  menuIcon: {
    color: colors.brand.orangeSoft,
    fontSize: 15,
    fontWeight: '700',
  },
  menuItemCopy: {
    flex: 1,
    marginLeft: 12,
  },
  menuItemTitle: {
    color: colors.text.heading,
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: -0.2,
  },
  menuItemDescription: {
    color: colors.text.muted,
    fontSize: 13,
    marginTop: 2,
  },
  menuChevron: {
    color: colors.text.mutedLight,
    fontSize: 20,
    fontWeight: '300',
  },
  menuSignOut: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    paddingVertical: 12,
    marginTop: 20,
    marginBottom: 10,
    borderRadius: 14,
    borderWidth: 0,
    backgroundColor: colors.status.errorBg,
  },
  menuSignOutText: {
    color: colors.status.error,
    fontSize: 16,
    fontWeight: '600',
  },
  profileHero: {
    alignItems: 'center',
    marginTop: 2,
    marginBottom: 12,
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderRadius: 18,
    borderWidth: 0,
    backgroundColor: colors.background.card,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  profileAvatarImg: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.navy[800],
    borderWidth: 1.5,
    borderColor: 'rgba(238,125,49,0.35)',
  },
  profileAvatarFallback: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.navy[800],
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(238,125,49,0.35)',
  },
  profileAvatarLetter: {
    color: colors.brand.orangeSoft,
    fontSize: 24,
    fontWeight: '700',
  },
  profileName: {
    color: colors.text.heading,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
  },
  profileMeta: {
    color: colors.text.muted,
    fontSize: 12,
    marginTop: 2,
    textAlign: 'center',
  },
  navLinkCard: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navLinkTitle: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '700',
  },
  navLinkMeta: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 2,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  statCard: {
    width: '48%',
    flexGrow: 1,
    backgroundColor: colors.background.card,
    borderColor: 'transparent',
    borderWidth: 0,
    padding: 14,
    borderRadius: 16,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  statValue: {
    color: colors.text.heading,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  statLabel: {
    color: colors.text.muted,
    fontSize: 12,
    marginTop: 4,
    fontWeight: '500',
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 0,
    marginTop: 8,
    backgroundColor: 'rgba(15,23,42,0.06)',
    borderRadius: 10,
    padding: 3,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    paddingVertical: 9,
    alignItems: 'center',
  },
  segmentButtonActive: {
    borderColor: 'transparent',
    backgroundColor: colors.white,
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  segmentButtonText: {
    color: colors.text.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  segmentButtonTextActive: {
    color: colors.text.heading,
  },
  optionRow: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 6,
  },
  optionRowSelected: {
    borderColor: colors.brand.orange,
    backgroundColor: 'rgba(238,125,49,0.06)',
  },
  optionTitle: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '600',
  },
  optionSubtitle: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 2,
  },
  dayCard: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  dayTitle: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '700',
  },
  timeRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  timeField: {
    flex: 1,
  },
});
