import { Platform, StyleSheet } from 'react-native';
import { safeBottom, safeTop } from '../layout/responsive';
import { colors } from '../theme';

/** @deprecated Prefer useLayout().safeTop */
export const SAFE_TOP = safeTop();
/** @deprecated Prefer useLayout().footerPad / safeBottom */
export const SAFE_BOTTOM = safeBottom();

/** Shared light-theme styles — premium kompakt panel. */
export const moduleStyles = StyleSheet.create({
  card: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 14,
    padding: 12,
    marginTop: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  cardTitle: {
    color: colors.text.heading,
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  cardMeta: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 2,
  },
  cardBody: {
    color: colors.text.body,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  pill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    backgroundColor: 'rgba(238,125,49,0.1)',
  },
  pillText: {
    color: colors.brand.orangeSoft,
    fontSize: 10,
    fontWeight: '700',
  },
  pillSuccess: {
    backgroundColor: colors.status.successBg,
  },
  pillSuccessText: {
    color: colors.status.success,
  },
  pillDanger: {
    backgroundColor: colors.status.errorBg,
  },
  pillDangerText: {
    color: colors.status.error,
  },
  pillMuted: {
    backgroundColor: colors.navy[800],
  },
  pillMutedText: {
    color: colors.text.muted,
  },
  actions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  actionBtn: {
    minWidth: '22%',
    flexGrow: 1,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: 'rgba(238,125,49,0.1)',
  },
  actionBtnText: {
    color: colors.brand.orangeSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  actionBtnPrimary: {
    backgroundColor: colors.brand.orange,
  },
  actionBtnPrimaryText: {
    color: colors.white,
  },
  actionBtnSuccess: {
    backgroundColor: colors.status.successBg,
  },
  actionBtnSuccessText: {
    color: colors.status.success,
  },
  actionBtnDanger: {
    backgroundColor: colors.status.errorBg,
  },
  actionBtnDangerText: {
    color: colors.status.error,
  },
  actionBtnMuted: {
    backgroundColor: colors.navy[800],
  },
  actionBtnMutedText: {
    color: colors.text.muted,
  },
  empty: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 14,
    padding: 16,
    marginTop: 12,
  },
  emptyTitle: {
    color: colors.text.heading,
    fontSize: 14,
    fontWeight: '700',
  },
  emptyText: {
    color: colors.text.body,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },
  sectionTitle: {
    color: colors.text.heading,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 16,
  },
  sectionSubtitle: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 2,
  },
  fabRow: {
    marginTop: 6,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  primaryButton: {
    borderRadius: 12,
    backgroundColor: colors.brand.orange,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(238,125,49,0.3)',
    backgroundColor: 'rgba(238,125,49,0.06)',
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: colors.brand.orangeSoft,
    fontSize: 12,
    fontWeight: '700',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    color: colors.text.heading,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
    fontSize: 14,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    color: colors.text.heading,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
    fontSize: 14,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  label: {
    color: colors.text.muted,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 10,
    marginBottom: 5,
  },
  switchRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  switchLabel: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  hint: {
    color: colors.text.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  errorText: {
    color: colors.status.error,
    fontSize: 12,
    marginTop: 8,
    lineHeight: 17,
  },
  successText: {
    color: colors.status.success,
    fontSize: 12,
    marginTop: 8,
    lineHeight: 17,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(16, 33, 51, 0.4)',
    justifyContent: 'flex-end',
    paddingTop: SAFE_TOP,
  },
  modalSheet: {
    backgroundColor: colors.background.card,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: colors.border.input,
    maxHeight: '92%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border.soft,
  },
  modalTitle: {
    color: colors.text.heading,
    fontSize: 15,
    fontWeight: '700',
  },
  modalClose: {
    color: colors.brand.orangeSoft,
    fontSize: 13,
    fontWeight: '700',
  },
  modalBody: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: SAFE_BOTTOM + 14,
  },
  menuGroup: {
    marginTop: 16,
  },
  menuGroupTitle: {
    color: colors.brand.orangeSoft,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.9,
    marginBottom: 6,
    marginLeft: 2,
    textTransform: 'uppercase',
  },
  menuCard: {
    borderRadius: 14,
    backgroundColor: colors.background.card,
    borderWidth: 1,
    borderColor: colors.border.input,
    overflow: 'hidden',
  },
  menuItem: {
    minHeight: 52,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border.soft,
  },
  menuIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(238,125,49,0.1)',
  },
  menuIcon: {
    color: colors.brand.orangeSoft,
    fontSize: 14,
    fontWeight: '700',
  },
  menuItemCopy: {
    flex: 1,
    marginLeft: 10,
  },
  menuItemTitle: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '700',
  },
  menuItemDescription: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 1,
  },
  menuChevron: {
    color: colors.text.mutedLight,
    fontSize: 18,
    fontWeight: '300',
  },
  menuSignOut: {
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 16,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(193,60,44,0.22)',
    backgroundColor: colors.status.errorBg,
  },
  menuSignOutText: {
    color: colors.status.error,
    fontSize: 13,
    fontWeight: '700',
  },
  profileHero: {
    alignItems: 'center',
    marginTop: 2,
    marginBottom: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
  },
  profileAvatarImg: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.navy[800],
    borderWidth: 1.5,
    borderColor: 'rgba(238,125,49,0.35)',
  },
  profileAvatarFallback: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.navy[800],
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(238,125,49,0.35)',
  },
  profileAvatarLetter: {
    color: colors.brand.orangeSoft,
    fontSize: 24,
    fontWeight: '700',
  },
  profileName: {
    color: colors.text.heading,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
  },
  profileMeta: {
    color: colors.text.muted,
    fontSize: 12,
    marginTop: 2,
    textAlign: 'center',
  },
  navLinkCard: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navLinkTitle: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '700',
  },
  navLinkMeta: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 2,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  statCard: {
    width: '48%',
    flexGrow: 1,
    backgroundColor: colors.background.card,
    borderColor: colors.border.input,
    borderWidth: 1,
    padding: 12,
    borderRadius: 12,
  },
  statValue: {
    color: colors.text.heading,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  statLabel: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 2,
    fontWeight: '500',
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    paddingVertical: 8,
    alignItems: 'center',
  },
  segmentButtonActive: {
    borderColor: colors.brand.orange,
    backgroundColor: 'rgba(238,125,49,0.08)',
  },
  segmentButtonText: {
    color: colors.text.muted,
    fontSize: 11,
    fontWeight: '600',
  },
  segmentButtonTextActive: {
    color: colors.brand.orangeSoft,
  },
  optionRow: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 6,
  },
  optionRowSelected: {
    borderColor: colors.brand.orange,
    backgroundColor: 'rgba(238,125,49,0.06)',
  },
  optionTitle: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '600',
  },
  optionSubtitle: {
    color: colors.text.muted,
    fontSize: 11,
    marginTop: 2,
  },
  dayCard: {
    borderWidth: 1,
    borderColor: colors.border.input,
    backgroundColor: colors.background.card,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  dayTitle: {
    color: colors.text.heading,
    fontSize: 13,
    fontWeight: '700',
  },
  timeRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  timeField: {
    flex: 1,
  },
});
