import { Platform, StyleSheet } from 'react-native';
import { safeBottom, safeTop } from '../layout/responsive';

/** @deprecated Prefer useLayout().safeTop — kept for moduleStyles static values */
export const SAFE_TOP = safeTop();
/** @deprecated Prefer useLayout().safeBottom */
export const SAFE_BOTTOM = safeBottom();

/** Shared dark-theme styles for hekim panel module screens. */
export const moduleStyles = StyleSheet.create({
  card: {
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#14283B',
    borderRadius: 18,
    padding: 16,
    marginTop: 12,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  cardTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    flex: 1,
  },
  cardMeta: {
    color: '#94A7B9',
    fontSize: 12,
    marginTop: 4,
  },
  cardBody: {
    color: '#B7C4D3',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    backgroundColor: 'rgba(245,138,69,0.14)',
  },
  pillText: {
    color: '#F3A26B',
    fontSize: 11,
    fontWeight: '800',
  },
  pillSuccess: {
    backgroundColor: 'rgba(77,189,140,0.16)',
  },
  pillSuccessText: {
    color: '#7ED2AB',
  },
  pillDanger: {
    backgroundColor: 'rgba(224,104,122,0.16)',
  },
  pillDangerText: {
    color: '#F09AA8',
  },
  pillMuted: {
    backgroundColor: 'rgba(148,167,185,0.14)',
  },
  pillMutedText: {
    color: '#94A7B9',
  },
  actions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  actionBtn: {
    minWidth: '22%',
    flexGrow: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(245,138,69,0.14)',
  },
  actionBtnText: {
    color: '#F3A26B',
    fontSize: 12,
    fontWeight: '800',
  },
  actionBtnPrimary: {
    backgroundColor: '#F58A45',
  },
  actionBtnPrimaryText: {
    color: '#1A2B3C',
  },
  actionBtnSuccess: {
    backgroundColor: 'rgba(77,189,140,0.18)',
  },
  actionBtnSuccessText: {
    color: '#7ED2AB',
  },
  actionBtnDanger: {
    backgroundColor: 'rgba(224,104,122,0.18)',
  },
  actionBtnDangerText: {
    color: '#F09AA8',
  },
  actionBtnMuted: {
    backgroundColor: 'rgba(148,167,185,0.12)',
  },
  actionBtnMutedText: {
    color: '#AEBECD',
  },
  empty: {
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#14283B',
    borderRadius: 20,
    padding: 22,
    marginTop: 20,
  },
  emptyTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  emptyText: {
    color: '#B7C4D3',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    marginTop: 22,
  },
  sectionSubtitle: {
    color: '#94A7B9',
    fontSize: 12,
    marginTop: 4,
  },
  fabRow: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  primaryButton: {
    borderRadius: 14,
    backgroundColor: '#F58A45',
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  primaryButtonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: '#1A2B3C',
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(245,138,69,0.45)',
    backgroundColor: 'rgba(245,138,69,0.12)',
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: '#F3A26B',
    fontSize: 13,
    fontWeight: '800',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#0F2132',
    borderRadius: 14,
    color: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 14 : 10,
    fontSize: 15,
    marginTop: 14,
  },
  input: {
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#0F2132',
    borderRadius: 14,
    color: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 14 : 10,
    fontSize: 15,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  label: {
    color: '#AEBECD',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 14,
    marginBottom: 8,
  },
  switchRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  switchLabel: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  hint: {
    color: '#94A7B9',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
  },
  errorText: {
    color: '#F09AA8',
    fontSize: 13,
    marginTop: 12,
    lineHeight: 18,
  },
  successText: {
    color: '#7ED2AB',
    fontSize: 13,
    marginTop: 12,
    lineHeight: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(6, 12, 20, 0.72)',
    justifyContent: 'flex-end',
    paddingTop: SAFE_TOP,
  },
  modalSheet: {
    backgroundColor: '#122536',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: '#2B4055',
    maxHeight: '92%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#263D52',
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  modalClose: {
    color: '#F3A26B',
    fontSize: 14,
    fontWeight: '800',
  },
  modalBody: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: SAFE_BOTTOM + 20,
  },
  menuGroup: {
    marginTop: 24,
  },
  menuGroupTitle: {
    color: '#F3A26B',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginBottom: 10,
    marginLeft: 4,
  },
  menuCard: {
    borderRadius: 20,
    backgroundColor: '#14283B',
    borderWidth: 1,
    borderColor: '#2B4055',
    overflow: 'hidden',
  },
  menuItem: {
    minHeight: 70,
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemBorder: {
    borderTopWidth: 1,
    borderTopColor: '#263D52',
  },
  menuIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245,138,69,0.12)',
  },
  menuIcon: {
    color: '#F3A26B',
    fontSize: 18,
    fontWeight: '700',
  },
  menuItemCopy: {
    flex: 1,
    marginLeft: 12,
  },
  menuItemTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  menuItemDescription: {
    color: '#94A7B9',
    fontSize: 11,
    marginTop: 3,
  },
  menuChevron: {
    color: '#7E94A9',
    fontSize: 26,
    fontWeight: '300',
  },
  menuSignOut: {
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 26,
    marginBottom: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(224,104,122,0.35)',
    backgroundColor: 'rgba(224,104,122,0.08)',
  },
  menuSignOutText: {
    color: '#F09AA8',
    fontSize: 14,
    fontWeight: '800',
  },
  profileHero: {
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 18,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#14283B',
  },
  profileAvatarImg: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#1B2E40',
    borderWidth: 2,
    borderColor: 'rgba(245,138,69,0.45)',
  },
  profileAvatarFallback: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#1B2E40',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(245,138,69,0.45)',
  },
  profileAvatarLetter: {
    color: '#F3A26B',
    fontSize: 34,
    fontWeight: '800',
  },
  profileName: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 12,
    textAlign: 'center',
  },
  profileMeta: {
    color: '#94A7B9',
    fontSize: 13,
    marginTop: 4,
    textAlign: 'center',
  },
  navLinkCard: {
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#14283B',
    borderRadius: 16,
    padding: 14,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navLinkTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  navLinkMeta: {
    color: '#94A7B9',
    fontSize: 12,
    marginTop: 3,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  statCard: {
    width: '48%',
    flexGrow: 1,
    backgroundColor: '#14283B',
    borderColor: '#2B4055',
    borderWidth: 1,
    padding: 14,
    borderRadius: 16,
  },
  statValue: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  statLabel: {
    color: '#AEBECD',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '600',
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#0F2132',
    paddingVertical: 11,
    alignItems: 'center',
  },
  segmentButtonActive: {
    borderColor: '#F58A45',
    backgroundColor: 'rgba(245,138,69,0.14)',
  },
  segmentButtonText: {
    color: '#94A7B9',
    fontSize: 12,
    fontWeight: '700',
  },
  segmentButtonTextActive: {
    color: '#F3A26B',
  },
  optionRow: {
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#0F2132',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 8,
  },
  optionRowSelected: {
    borderColor: '#F58A45',
    backgroundColor: 'rgba(245,138,69,0.12)',
  },
  optionTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  optionSubtitle: {
    color: '#94A7B9',
    fontSize: 12,
    marginTop: 3,
  },
  dayCard: {
    borderWidth: 1,
    borderColor: '#2B4055',
    backgroundColor: '#14283B',
    borderRadius: 16,
    padding: 14,
    marginTop: 10,
  },
  dayTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  timeRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  timeField: {
    flex: 1,
  },
});
